### PR TITLE
Samed

### PR DESCRIPTION
**Pull request by sameddii**
added some exercises tasks

### CODE REVIEW

**Comment by lbaidachenko** [comment]
Hi Samed, great job! 
Just one question: Are we suppose to update the master branch or the develop branch instead with this pull request?

**Comment by sameddii** [comment]
Yes, actually I wanted to update master with this one so we have updated version of master just a bit to not be too far with commits.

**Comment by sameddii** [comment]
> Hi Samed, great job! Just one question: Are we suppose to update the master branch or the develop branch instead with this pull request?

[](url)

**Comment by sameddii** [comment]
Yes, actually I wanted to update master with this one so we have updated version of master just a bit to not be too far with commits

**Review by lbaidachenko — APPROVED** [review]

**Pull request merged**
